services:
  app:
    build: .
    image: flask-devops
    container_name: flask_app
    environment:
      DB_HOST: db
      DB_NAME: devopsdb
      DB_USER: devops
      DB_PASSWORD: devops
    depends_on:
      - db
    networks:
      - back_net

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: devopsdb
      POSTGRES_USER: devops
      POSTGRES_PASSWORD: devops
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - back_net

  seed_runner:
    image: flask-devops
    container_name: seed_runner
    command: python seed/run_seed.py
    environment:
      DB_HOST: db
      DB_NAME: devopsdb
      DB_USER: devops
      DB_PASSWORD: devops
    depends_on:
      - db
    volumes:
      - seed_output:/seed_output
    networks:
      - back_net
    restart: "no"


  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx_logs:/var/log/nginx
    depends_on:
      - app
    networks:
      - front_net
      - back_net

networks:
  back_net:
  front_net:

volumes:
  db_data:
  seed_output:
  nginx_logs:
