services:
  app:
    build: .
    image: flask-devops
    container_name: flask_app
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_NAME: devopsdb
      DB_USER: devops
      DB_PASSWORD: devops
    depends_on:
      - db
    networks:
      - back_net

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: devopsdb
      POSTGRES_USER: devops
      POSTGRES_PASSWORD: devops
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - back_net

  seed_runner:
    image: flask-devops
    container_name: seed_runner
    command: python seed/run_seed.py
    environment:
      DB_HOST: db
      DB_NAME: devopsdb
      DB_USER: devops
      DB_PASSWORD: devops
    depends_on:
      - db
    volumes:
      - seed_output:/seed_output
    networks:
      - back_net
    restart: "no"

networks:
  back_net:

volumes:
  db_data:
  seed_output:
